$kind: http-request
name: Create Role
method: POST
url: '{{baseUrl}}/api/roles'
order: 4000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "name": "Editor",
      "description": "Can edit posts",
      "permissions": []
    }
