$kind: http-request
name: Update Role
method: PUT
url: '{{baseUrl}}/api/roles/{{roleId}}'
order: 5000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "name": "Editor",
      "description": "Updated description",
      "permissions": []
    }
