import { defineConfig, Plugin } from 'vite';
import react from '@vitejs/plugin-react';

// The admin app is served under Vite base '/admin/', so a bare '/admin' (no
// trailing slash) 404s before the SPA loads. Redirect it to '/admin/' — this
// mirrors the production nginx `location = /admin { return 301 /admin/; }`.
// Runs before the proxy middleware so the bare path never reaches the admin server.
function adminTrailingSlashRedirect(): Plugin {
  return {
    name: 'admin-trailing-slash-redirect',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url || '';
        if (url === '/admin' || url.startsWith('/admin?')) {
          res.statusCode = 301;
          res.setHeader('Location', `/admin/${url.slice('/admin'.length)}`);
          res.end();
          return;
        }
        next();
      });
    },
  };
}

export default defineConfig({
  plugins: [react(), adminTrailingSlashRedirect()],

  // @headtilts/shared compiles to CommonJS. Vite must pre-bundle it to ESM
  // so named imports are available in the browser.
  optimizeDeps: {
    include: ['@headtilts/shared'],
    force: true,
    esbuildOptions: {
      target: 'es2020',
    },
  },
  server: {
    port: 5173, // unified dev entry point
    proxy: {
      // Forward all /admin/* (HTML, JS modules, HMR WS) to the admin dev server.
      // Admin runs with base: '/admin/' so its own @vite paths are prefixed
      // /admin/@vite/... — they all match here and land at the right server.
      '/admin': {
        target: 'http://localhost:5174',
        changeOrigin: true,
        ws: true,
      },
      // Forward API calls to the Express server.
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
      // Public health check — used by StatusPage.
      '/health': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
      // Crawler files are generated by the API but must be reachable
      // from the site root.
      '/robots.txt': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
      '/sitemap.xml': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
      // Uploaded media (renditions live under /uploads on the API).
      '/uploads': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
    },
  },
});
