$kind: http-request
name: Update Settings
method: PUT
url: '{{baseUrl}}/api/settings'
order: 2000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "site_title": "My Site",
      "site_tagline": "Welcome",
      "posts_per_page": "10"
    }
