CREATE TABLE `ActivityLog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `site` VARCHAR(20) NOT NULL,
  `level` VARCHAR(10) NOT NULL DEFAULT 'info',
  `category` VARCHAR(40) NOT NULL,
  `action` VARCHAR(80) NOT NULL,
  `actorId` VARCHAR(36) NULL,
  `actorEmail` VARCHAR(255) NULL,
  `targetType` VARCHAR(40) NULL,
  `targetId` VARCHAR(40) NULL,
  `targetTitle` VARCHAR(255) NULL,
  `ip` VARCHAR(45) NULL,
  `userAgent` VARCHAR(500) NULL,
  `path` VARCHAR(500) NULL,
  `method` VARCHAR(10) NULL,
  `statusCode` INT NULL,
  `duration` INT NULL,
  `meta` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `ActivityLog_timestamp_idx` (`timestamp`),
  INDEX `ActivityLog_site_timestamp_idx` (`site`, `timestamp`),
  INDEX `ActivityLog_level_timestamp_idx` (`level`, `timestamp`),
  INDEX `ActivityLog_category_timestamp_idx` (`category`, `timestamp`),
  INDEX `ActivityLog_actorId_timestamp_idx` (`actorId`, `timestamp`),
  INDEX `ActivityLog_action_timestamp_idx` (`action`, `timestamp`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
